# -*- coding: utf-8 -*-
"""bankMang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10YyGkqY9c-zOFzWNZ8UN82CvEIfifoaW
"""

usernames = ["Sreeram12" ,  "Samhitha12" ,"Lakshmi12" ,  "SaiSree12"]
accounts = ["1234006","1234009","1234007","1234008"]
balance = [300000 ,  234000 ,342561,  452362,]
pins = []
bank = {"username" : usernames, "ac_numbers" : accounts, "balance" : balance, "pins" : []
        }

a = bank.get("username")[0]
print(a)

bank = {"Username1" : "Sreeram12" , "Username2" : "Samhitha12" , "Username3" : "Lakshmi12" , "Username4" : "SaiSree12",
        "Sreeram12" : "123456" , "Samhitha12" : "234576" , "Lakshmhi12" : "345678" , "SaiSree12" : "456789",
        "123456" : "123" , "234567" : "234" , "345678" : "345" , "456789" : "456",
        "Sreeram12a" : [300000] , "Samhitha12a" : [234000] , "Lakshmhi12a" : [342561], "SaiSree12a" : [452362]
       }
d = input("Kindly enter your username: ")
x = d + "a"
a = bank.get(x)
print(x)

b = int(input("Enter how much you want to deposit : "))
f = a[0] + b
print(f)
a[0] = f
print(bank)

bank = {"Username1" : "Sreeram12" , "Username2" : "Samhitha12" , "Username3" : "Lakshmi12" , "Username4" : "SaiSree12",
        "Sreeram12" : "123456" , "Samhitha12" : "234576" , "Lakshmhi12" : "345678" , "SaiSree12" : "456789",
        "123456" : "123" , "234567" : "234" , "345678" : "345" , "456789" : "456",
        "Sreeram12a" : 300000 , "Samhitha12a" : 234000 , "Lakshmhi12a" : 342561, "SaiSree12a" : 452362
       }
        
c = input("Kindly enter your name to use your bank account : ")
d = input("Kindly enter your username: ")
e = input("Kindly enter your account number : ")
while True:
  if d in bank.values():
    if e in bank.values():  
      print("Hi ", c)
      print("Kindly enter the number of one of the following operations which you want to perform" ,'\n' , "1. Deposit" , '\n' , "2. Withdraw" , '\n' , "3. Check Balance" )
      m = int(input("Please enter the number : "))
      if m == 1:
        #a = int(input("Enter the current amount which you have in your account : "))
        balance = bank.values(d+"a")
        p = input("Kindly enter your pin number: ")
        if p in bank.values():
          b = int(input("Enter how much you want to deposit : "))
          f = a + b
          print("Your current amount is ",f)
          g = input("Do you want to perform any other operation : ")
          if g == "Yes" or "yes":
            pass
          else:
            print("Thank you for using our bank.")
          break
        else:
          print("I am sorry, but you have entered the incorrect pin number!")
      elif m == 2:
        h = int(input("Enter the current amount which you have in your account : "))
        pi = int(input("Kindly enter the pin number: "))
        if pi in bank.values():
          i = int(input("Enter how much you want to deposit : "))
          j = h - i
          print("Your current amount is ", j)
          k = input("Do you want to perform any other operation : ")
          if k == "Yes" or "yes":
            pass
          else:
            print("Thank you for using our bank")
          break
        else:
          print("I am sorry, but you have entered the incorrect pin number!")
      elif m == 3:
        pin = int(input("Kindly enter your pin number:"))
        if pin in bank.values():
          print("Your current amount in the bank is 335265")
          l  = input("Do you want to perform any other operation : ")
          if l == "Yes" or "yes":
            pass
          else:
            print("Thank you for using our bank")
          break
        else:
          print("I am sorry, but you have entered the incorrect pin number!")
    else:
      print("I am sorry, but there is no account registered with that number!!")
      print("Try again")
    break
  else:
    print("I am sorry, but there is no username registered with that name!!")
    print("Try again")
  break

bank = {"Username1" : "Sreeram12" , "Username2" : "Samhitha12" , "Username3" : "Lakshmi12" , "Username4" : "SaiSree12",
        "Sreeram12" : "123456" , "Samhitha12" : "234576" , "Lakshmhi12" : "345678" , "SaiSree12" : "456789",
        "123456" : "123" , "234567" : "234" , "345678" : "345" , "456789" : "456",
        "Sreeram12a" : 300000 , "Samhitha12a" : 234000 , "Lakshmhi12a" : 342561, "SaiSree12a" : 452362
       }

d = input("Kindly enter your username: ")
x = d + "a"
if bank.values()
print(balance)



NamesOFClients = ['Jomhel Dulla', 'Benny Salde', 'Jeremy Eriman', 'Given Bariacto', 'Carlan Pelobello', 'Ryan Manaay', 'Daniel Bandiola']
ClientPins = ['0001', '0002', '0003', '0004', '0005', '0006', '0007']
ClientBalances = [10000, 20000, 30000, 40000, 50000, 60000, 70000]
ClientDeposition = 0
ClientWithdrawal = 0
ClientBalance = 0
disk1 = 1
disk2 = 7
u = 0
while True:
# os.system("cls")
print("************************************************************")
print("========== WELCOME TO ITSOURCECODE BANKING SYSTEM ==========")
print("************************************************************")
print("========== (a). Open New Client Account ============")
print("========== (b). The Client Withdraw a Money ============")
print("========== (c). The Client Deposit a Money ============")
print("========== (d). Check Clients &amp; Balance ============")
print("========== (e). Quit ============")
print("************************************************************")

EnterLetter = input("Select a Letter from the Above Box menu : ")
if EnterLetter == "a":
print(" Letter a is Selected by the Client")
NumberOfClient = eval(input("Number of Clients : "))
u = u + NumberOfClient

if u &gt; 7:
print("\n")
print("Client registration exceed reached or Client registration too low")
u = u - NumberOfClient
else:
while disk1 &lt;= u:
name = input("Write Your Fullname : ")
NamesOFClients.append(name)
pin = str(input("Please Write a Pin to Secure your Account : "))
ClientPins.append(pin)
ClientBalance = 0
ClientDeposition = eval(input("Please Insert a Money to Deposit to Start an Account : "))
ClientBalance = ClientBalance + ClientDeposition
ClientBalances.append(ClientBalance)
print("\nName=", end=" ")
print(NamesOFClients[disk2])
print("Pin=", end=" ")
print(ClientPins[disk2])
print("Balance=", "P", end=" ")
print(ClientBalances[disk2], end=" ")
disk1 = disk1 + 1
disk2 = disk2 + 1
print("\nYour name is added to Client Table")
print("Your pin is added to Client Table")
print("Your balance is added to Client Table")
print("----New Client account created successfully !----")
print("\n")
print("Your Name is Available on the Client list now : ")
print(NamesOFClients)
print("\n")
print("Note! Please remember the Name and Pin")
print("========================================")

mainMenu = input(" Press Enter Key to go Back to Main Menu to Conduct Another Transaction or Quit_")
elif EnterLetter == "b":
v = 0
print(" letter b is Selected by the Client")
while v &lt; 1:
w = -1
name = input("Please Insert a name : ")
pin = input("Please Insert a pin : ")
while w &lt; len(NamesOFClients) - 1:
w = w + 1
if name == NamesOFClients[w]:
if pin == ClientPins[w]:
v = v + 1
print("Your Current Balance:", "P", end=" ")
print(ClientBalances[w], end=" ")
print("\n")
ClientBalance = (ClientBalances[w])
ClientWithdrawal = eval(input("Insert value to Withdraw : "))
if ClientWithdrawal &gt; ClientBalance:
deposition = eval(input(
"Please Deposit a higher Value because your Balance mentioned above is not enough : "))
ClientBalance = ClientBalance + deposition
print("Your Current Balance:", "P", end=" ")
print(ClientBalance, end=" ")
ClientBalance = ClientBalance - ClientWithdrawal
print("-\n")
print("----Withdraw Successfully!----")
ClientBalances[w] = ClientBalance
print("Your New Balance: ", "P", ClientBalance, end=" ")
print("\n\n")
else:
ClientBalance = ClientBalance - ClientWithdrawal
print("\n")
print("----Withdraw Successfully!----")
ClientBalances[w] = ClientBalance
print("Your New Balance: ", "P", ClientBalance, end=" ")
print("\n")
if v &lt; 1:
print("Your name and pin does not match!\n")
break
mainMenu = input(" Press Enter Key to go Back to Main Menu to Conduct Another Transaction or Quit_")
elif EnterLetter == "c":
print("Letter c is selected by the Client")
x = 0
while x &lt; 1:
w = -1
name = input("Please Insert a name : ")
pin = input("Please Insert a pin : ")
while w &lt; len(NamesOFClients) - 1:
w = w + 1
if name == NamesOFClients[w]:
if pin == ClientPins[w]:
x = x + 1
print("Your Current Balance: ", "P", end=" ")
print(ClientBalances[w], end=" ")
ClientBalance = (ClientBalances[w])
print("\n")
ClientDeposition = eval(input("Enter the value you want to deposit : "))
ClientBalance = ClientBalance + ClientDeposition
ClientBalances[w] = ClientBalance
print("\n")
print("----Deposition successful!----")
print("Your New Balance: ", "P", ClientBalance, end=" ")
print("\n")
if x &lt; 1:
print("Your name and pin does not match!\n")
break
mainMenu = input(" Press Enter Key to go Back to Main Menu to Conduct Another Transaction or Quit_")
elif EnterLetter == "d":
print("Letter d is selected by the Client")
w = 0
print("Client name list and balances mentioned below : ")
print("\n")
while w &lt;= len(NamesOFClients) - 1:
print("-&gt;.Customer =", NamesOFClients[w])
print("-&gt;.Balance =", "P", ClientBalances[w], end=" ")

print("\n")
w = w + 1
mainMenu = input(" Press Enter Key to go Back to Main Menu to Conduct Another Transaction or Quit_ ")
elif EnterLetter == "e":
print("letter e is selected by the client")
print("Thank you for using our banking system!")
print("\n")
print("Thank You and Come again")
print("God Bless")
break
else:
print("Invalid option selected by the Client")
print("Please Try again!")

mainMenu = input("Press Enter Key to go Back to Main Menu to Conduct Another Transaction or Quit_")

NamesOFClients = ['Jomhel Dulla', 'Benny Salde', 'Jeremy Eriman', 'Given Bariacto', 'Carlan Pelobello', 'Ryan Manaay', 'Daniel Bandiola']
ClientPins = ['0001', '0002', '0003', '0004', '0005', '0006', '0007']
ClientBalances = [10000, 20000, 30000, 40000, 50000, 60000, 70000]
ClientDeposition = 0
ClientWithdrawal = 0
ClientBalance = 0

w = index number of list

ClientBalance = ClientBalances[2] + ClientDeposition
ClientBalances[2] = ClientBalance

newbalance = balance + addingmoney
newbalance = balance + withdrawing money

balance[index] = newbalance