# -*- coding: utf-8 -*-
"""Copy of 21. Exercise Questions_lambda_map_filter_reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2RAChlW1idfIZCAHKUVNAstvWN3H5G9

These questions are from yesterday's class. Start them

#Lambda Functions
1. Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument, also create a lambda function that multiplies argument x with argument y and print the result.
2. Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.
3. Write a Python program to sort a list of tuples using Lambda.
4. Write a Python program to sort a list of dictionaries using Lambda.
5. Write a Python program to filter a list of integers using Lambda.
6. Write a Python program to square and cube every number in a given list of integers using Lambda.
7. Write a Python program to find if a given string starts with a given character using Lambda.
8. Write a Python program to extract year, month, date and time using Lambda.
9. Write a Python program to check whether a given string is number or not using Lambda.
10. Write a Python program to create Fibonacci series upto n using Lambda.
11. Write a Python program to find intersection of two given arrays using Lambda.
12. Write a Python program to rearrange positive and negative numbers in a given array using Lambda.
13. Write a Python program to count the even, odd numbers in a given array of integers using Lambda.
14. Write a Python program to find the values of length six in a given list using Lambda.
15. Write a Python program to add two given lists using map and lambda.
"""

# Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument, 
# also create a lambda function that multiplies argument x with argument y and print the result.

add = lambda x : f"the new number after adding 15 is {x+15}"
ask = int(input("Enter a number: "))
print(add(ask))

mul = lambda x,y : f"the multiplication of {x} & {y} is {x*y} "
print(mul(3,60))

# Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.
ask = int(input("enter a number: "))

mul = lambda x : x*ask
print(mul(4))

# Write a Python program to sort a list of tuples using Lambda.
x = (1,2)
a = 1
b=3
temp = 1
a= b
b= temp

# Write a Python program to filter a list of integers using Lambda.

x = [1,2,"hii", 7.5,"py",3,4]
num = list(filter(lambda a : type(a) == int, x))
print(num)

import time

r=time.localtime()
r.tm_year

dir(time)

"""#Map
1. Write a program to calculate the square of all numbers in a list. 
2. Write a python program to determine the grades of students based on percentages, which are provided in a list.
3. Write a program to find out if words in a list are pallindromes. 
4. Write a program to determine if words in a list begin with a capital letter.

"""

# iterable examples include: lists, tuples, and ranges
l1 = range(1,25)
def rev(x):
  x=x/2
  return x
# map(function, iterable)
b = map(rev,l1)
print(list(b))

"""#Filter
1. Write a python program to find all words that begin with the letter 'c'
2. Write a program to filter all pallindroms from a list and output into a list. 
3. Write a python program to take all names of students in class and capitalize them. Create a list of items that begin only with 'N' 
4. Write a program to filter all positive numbers into a list. 

"""