# -*- coding: utf-8 -*-
"""Guessing Games _B2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17jJkr8SWDQbOlub9I7zho_mGdpx49Eco
"""

# Create a  Luck game. The following are the details
# Input from user--Name, color
# CHoose a color: Red-1, Blue-2, Black-3, Yellow-4, Green-5
# show input-----------------------------------------------------
# Player will get the prize
# 500 to play. If you win, you get Blue-600, Red-0, Black-1000, Yellow-800, Green-700. If you lose you pay 500. 
# If you select a number out of range (1,5),you lose 10 rupees for every run

# levels of the game. Level 1-- Easy: 1-5, Level 2--moderate : 1-10, Level 3 --Hard : 1-50, Level 5 -- Expert: 1-100, level 6 impossible --1-1000
#maximum tries = 3------------------


# Example user journey
# Enter a color=Blue==>random number(generate)=>returns 1, 1 maps to Red. Red==> You lost all money.

# - guessing colors - easy
# luck based game  - complex

ask = input("enter yes or no: ")
if ask.upper() == "YES" :



ticket = input("enter ticket number: ")
name = input('enter ur name: ')
print("\n please choose the colours given below ")
print( "1)  red \t 2) blue \t 3) black \t 4) yellow \t 5)  Green \n\n")

import random

money = 500

i = 1
while i <= 4 :
  color = input("Select a color: ")
  if color.lower() == "red" or color.lower() == "black" or color.lower() == "blue" or color.lower() == "green" or color.lower() == "yellow" :
    print("")
    print(f"your selction is : {color.lower()}")
    select = random.randint(1,10)    # generates a random number 
    if select == 1 :   
      print("Bad luck! You Just lost all the money. Pay again to play ")
      money = money-500 # money = 0
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = 0 \n\n ")
      break
    
    elif select == 2 :   
      print("Wow! You Just won 600. Play again to win more!! ")
      money = money + 600
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money}  \n\n")
      if money == 0 :
        break

    elif select == 3 :   
      print("Biggest Luck of the Centuray! You Just won 1000. Play again to win more!! ")
      money = money + 1000
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break       

    elif select == 4 :   # 4 == "Yellow"
      print("Amazing! You Just won 700. Play again to win more!! ")
      money = money + 700
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break

    elif select == 5 :   # 5 == "Green"
      print("You got Lucky! You Just won 600. Play again to win more!! ")
      money = money + 800
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break
    
    else : 
      print("You just lost 100! As You did not get any lucky number, Play again to win more!! ")
      money = money - 100
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break

  else :
    print( "you selcted color is not available")
  
  i = i+1

ticket = input("enter ticket number: ")
name = input('enter ur name: ')
print("\n please choose the colours given below ")
print( "1)  red \t 2) blue \t 3) black \t 4) yellow \t 5)  Green \n\n")

import random

money = 500
C = ["red","blue","green", "yellow","black"]

i = 1
while i <= 4 :
  color = input("Select a color: ")
  if color.lower()  in C :
    print("")
    print(f"your selction is : {color.lower()}")
    select = random.randint(1,10)    # generates a random number 
    if select == 1 :   
      print("Bad luck! You Just lost all the money. Pay again to play ")
      money = money-500 # money = 0
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = 0 \n\n ")
      break
    
    elif select == 2 :   
      print("Wow! You Just won 600. Play again to win more!! ")
      money = money + 600
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money}  \n\n")
      if money == 0 :
        break

    elif select == 3 :   
      print("Biggest Luck of the Centuray! You Just won 1000. Play again to win more!! ")
      money = money + 1000
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break       

    elif select == 4 :   # 4 == "Yellow"
      print("Amazing! You Just won 700. Play again to win more!! ")
      money = money + 700
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break

    elif select == 5 :   # 5 == "Green"
      print("You got Lucky! You Just won 600. Play again to win more!! ")
      money = money + 800
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break
    
    else : 
      print("You just lost 100! As You did not get any lucky number, Play again to win more!! ")
      money = money - 100
      print(f"Number is : {select} \t\t | Color : {color.lower()} \t\t|\t\t Balance = {money} \n\n")
      if money == 0 :
        break

  else :
    print( "you selcted color is not available")
  
  i = i+1

color = ["red","blue","green", "Yellow","black"]

# Guessing colors
import random
print("Hii, This is a Guessing Colors Game!!!")
print("Instructions: You Just need to type the Color which computer has picked up!!!")
guess = input("Enter your guess: ")
#color = {1:"red", 2:""}

color = ["red","blue","green", "Yellow","black"]
picked = random.choice(color)
print(color_picked)
if guess.capitalize() == picked.capitalize() :
  print(f"Congratulation!!!! {guess} is the correct Guess")
else :
  print(f"You Lost!! \t{picked} is the color picked, \tbut ur guess is {guess}")

# Guessing colors
import random
print("Hii, This is a Guessing Colors Game!!!")
print("Instructions: You Just need to type the Color which computer has picked up!!!")

#color = {1:"red", 2:""}

color = ["red","blue","green", "yellow","black"]
picked = random.choice(color)
print(color)
print("please select a color from the above colors listed")
for i in range(3):
  guess = input("Enter your guess: ")
  if guess.capitalize() == picked.capitalize() :
    print(f"Congratulation!!!! {guess} is the correct Guess")
    #print("Congratulation!!!! {} is the correct {} Guess".format(guess,picked))
    break
  elif guess.lower()  not in color:
    print("Your entered color is not present")
  else :
    print(f"{guess} is Wrong Guess!! Try Again " )

if guess.capitalize() != picked.capitalize():
  print("You Lost!!!, Play Again")

help(str)

gave 5 color  to selsct one of them
the genaerating random number

if, elif, else
only if block we can write
elif, else--- we can use only elif or else withou specifying if block

if condition1 :
  body of the if block
elif condition2 :    ---> unlimited elif u can create
  body of the elif block
else :

a = 2
b= 3
if a>b :
  print("greater")
elif a== b:
  print("equal")
else :
  print("lesser")

1 = red, 2 = blue
type = red
if type = 1 :
  money = money + 200
  print()





#Guessing game   -----> sai sree code
#Level 1
import random
a = input("Enter your name to start the game: ")
print("Hi",a)
print("Welcome to ColourCodez")
print("Instructions - \n 1. This is a game entirely based on luck, so dont worry if you lose \n 2. These are the colours - Red,Blue,Green,Pink,Purple,Orange,Yellow,Black,White,Grey,Brown \n 3. Enjoy!!")
total = 0
b = input("Enter the name of any colour: ")
if b.lower() == "red" or b.lower == "black" or b.lower == "blue" or b.lower() == "green" or b.lower() == "pink" or b.lower() == "orange" or b.lower() == "purple" or b.lower() == "yellow":
  print("The colour you selected is :", {b.lower()})
  select = random.randint(1,5)
  print("select is ", select)
  if select == 1:
    print("Hurray!!, You got 800 points for the number you gave")
    total  = total + 800
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif select == 2:
    print("I am sorry but you have lost 500 points from your account")
    total  = total - 500
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif  select == 3:
    print("Awesome! You have just won 700")
    total = total + 700
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif select == 4:
    print("You have just lost 100!")
    total = total - 100
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif select == 5:
    print("Your luck seems to be working a lot today because you just won a jackpot of 5000")
    total = total + 5000
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)

else:
    #total = total - 100
    print("you lost 100!!")
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)

if select == 1:
    print("Hurray!!, You got 800 points for the number you gave")
    total  = total + 800
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif b == 2:
    print("I am sorry but you have lost 500 points from your account")
    total  = total - 500
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif b == 3:
    print("Awesome! You have just won 700")
    total = total + 700
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif b == 4:
    print("You have just lost 100!")
    total = total - 100
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)
  elif b == 5:
    print("Your luck seems to be working a lot today because you just won a jackpot of 5000")
    total = total + 5000
    print(f"Your selected number is : {select} \t\t | Your selected colour is  : {b.lower()} \t\t|\t\t Your current balance is = ",total)