# -*- coding: utf-8 -*-
"""ListExamples_B2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7YnbWUKm7xaOxxYgx0l5cBCY5N6w8f5
"""

x = 2
if x%2 == 0:
  print("even")
else :
  print("odd")

l = [1,3,5,2,89,67,44,24]
for i in l:
  if x % 2 == 0:
    print(i, "is even number")
  else :

l = [1,3,5,2,89,67,44,24]
sum = 0
for i in l:
  sum = sum + i

print(sum)

For Loops
A for loop iterates over a sequence of elements, executing the body of the loop for each element in the sequence.

Syntax:

for variable in sequence :  
    body

"""**range() function:**  https://www.programiz.com/python-programming/methods/built-in/range 

The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and stops before a specified number.

* The range() function is used to generate a sequence of numbers.
* Most common use of range() function in Python is to iterate sequence type (List, string etc.. ) with for and while loop.

####Syntax

```
range(start, stop, step)
```
Parameter Values & Parameter	Description


---

* **start**	{Optional} - An integer number specifying at which position to start. Default is 0
* **stop**	{Required} - An integer number specifying at which position to stop (not included).
 * Returns a sequence of numbers starting from 0 to stop - 1
* **step**	{Optional} - An integer number specifying the incrementation. Default is 1
"""

(a+(b + c))

planets=[] #1. Make empty List
for x in range(8): #2. looping function and
  name = input("Name of planet: ") #a. take input from user
  planets.append(name) #b. add name to list
print(planets)# 3. Print list

for j in range(1,11):
  product = 10*j   # j =1, 1x10 = 10; j=2 --> 2x10 = 20
  var = "10 x {} = "
  print (var.format(j), product )

#math tables
table = []
import numpy as np  # NumPy is a python library used for working with arrays.
for i in range(1,11):
  for j in range(1,11): 
    product = j*i
    table.append(product) 
print(table)
print("\n")
np.reshape(table,(10,10)) # reshaped with 10 rows and 10 columns

print("hello world \n" * 10)

print(4 / 2) # it gives the output as quoteint
print(5 % 2 ) # it gives the output as REMINDER OF the division


# % gives reminder of division

#a = [1,2,3,4,5,6,7,8,9]
even = []
odd = []
for  num in  range(1 , 21) :

  if num %  2 == 0 :
    even.append(num) # it add the num variable value into the even list varialbe

  else :
    odd.append(num) # it adds the number into the odd list

print("the even numbers in given range is : ", even)
print("the odd numbers in given range is : ", odd)

a = [1,2,3,4,5,6,7,8,9]

num = str(a[2])

if num

for i in range(1, 10) : # used to print numbers in sequnce with adding 1 
  print(i)

for i in range(10) : # used to print  from 0 to 9
  print(i)

for i in range(20, 10, -2) : # used to print backward numbers
  print(i)