# -*- coding: utf-8 -*-
"""OTP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZ7ejvXslS_o_3q_oaZaF78DobCgN1IO
"""

# Generate Random OTP, Passwords etc


----> to Generate random numbers or letters/ symbols------> use random Library

pycharm  - IDE
sublime text - IDE tools
Atom - editors
vs code- tool
python IDLE - tool

"""https://docs.python.org/3/library/random.html - random module/library

https://www.geeksforgeeks.org/python-ways-to-initialize-list-with-alphabets/ - ways to create aplabets

"""

random.randint(a, b)
Return a random integer N such that a <= N <= b. Alias for randrange(a, b+1).

random.choice(seq)
Return a random element from the non-empty sequence seq. If seq is empty, raises IndexError.

# generate an otp :
import random
otp = random.randint(1000, 9999)  # randint will pick a random number from the given range of numbers
print(otp)

import random
# randint will pick a random number from the given range of numbers
otp = ""
for i in range(4):
  x = str(random.randint(0,9))
  otp = otp + x

print(otp)

import random
x = random.randint(1000, 9999)  # randint will pick a random number from the given range of numbers
y = random.randint(1000,5000)
print(f"the sum of {x} + {y} is {x+y} ")
print("the sum of {} + {} is {}".format(x,y,x+y))

8291 + 3043

print(chr(65))
print(ord("a"))   # Return the Unicode code point for a one-character string.   - gives the ascii number for a particular character

# random password 
import random
# randint will pick a random number from the given range of numbers

capital = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
gen = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
           "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
           "!","@","&","*",".","~","_","-", 0,1,2,3,4,5,6,7,8,9]


#for i in range(26):



psw = ""
for i in range(8):
  x = str(random.choice(gen))
  psw = psw + x
  while x not in capital :  # specified a  condition that 1st charecter should be a Capital letter
    x = str(random.choice(gen))

print(psw)

small = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
symbol = ["!","@","&","*",".","~","_","-"]
numbers = [0,1,2,3,4,5,6,7,8,9]



"""Various examples in different coode: -- for otp generation

* https://www.geeksforgeeks.org/python-program-to-generate-one-time-password-otp/ 
* https://www.geeksforgeeks.org/strong-password-suggester-program/?ref=rp

"""

5446
4564
6454
4456