# -*- coding: utf-8 -*-
"""3. Python Classes - Lesson 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FVqjfotEernq02hAi6TH_DnPHFD13y4F

# concatenation
*duck typing*
"""

a = 'school' 
b= ' bus'
noun = a+b# -> concatenating --> putting them together
print(noun)
a=9
b=3
c=a+b
print(a+b)

s = "I am going to the market"
print("Tanay is",s[5:10],s[11:17],"school") #=> slicing a string, concatenate

name = 'Neville'
location = 'Hyderabad'
year  = 2020
fav_num = 10.8
fav_num1 = 3.9
fav2 = 7
fav3 = 3
fav = 18
print(name +" "+ location )
print(fav + year )
print(fav_num + fav_num1)

#concatenation
x = '20'
y = '30'
z = y+x
print(z)

x = 'two'
y = 'three'
z = x+y
print(z)

#indentation
x = 3
if (x>2):
  print(x)
  x = x**2
print(x)

#new line character
print(" First things first\n I will say all the\n words inside my head\n I'm fired and tired of the way things have been")

#tab character
print("This is\t new data")

#carriage return
print("first line start from here\rthis is second line")

#Slicing
a = "I went to the market"
b = 'I am string'
# 'I' ' ' 'a' 'm' ' ' 's' 't' 'r' 'i'  'n' 'g'
#  0   1   2   3   4   5   6   7   8    9   10
print(type(b))
print(len(b))
your_name = b[2 : 4]
print(your_name)