# -*- coding: utf-8 -*-
"""Quizz_Lists_solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X64flzZ7ORlTjNLMtdXeVyFaI1wSWrM9

https://colab.research.google.com/drive/1ihIrAbNhDU7W3c-mJivN-oKQZjSBUEjF?usp=sharing  -quizz questions
"""

l = ["python", "code", "kite", 1,2,3,45,6]
print("length of the list is " ,len(l))
print(l[4])
print(l[0].upper())
l[0] = l[0].upper()
print(l)
l.append("games")
print(l)
l.insert(3, 7.8)
print(l)
print(l[5])
l.pop(5)
print(l)
l.remove("code")
print(l)

"""1. Write a Python program to sum all the items in a list. Create lists with at least 6  -----> take list items as number to add all items in a list
2. Write a Python program to multiply all the items in the list created in (1).
3. Write a Python program to get the smallest number from a list.
4. Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings. (Sample List : ['abc', 'xyz', 'aba', '1221'])
5.  Write a Python program to remove duplicates from a list.
6. Write a Python program to check a list is empty or not. (look up)
7. Write a Python program to clone or copy a list.
8.  Write a Python program to find the list of words that are longer than 5 from a given list of words. create list with random animal names. 
9. Write a Python program to get the difference between the two lists. (create two lists with numbers. List size should be at least 5 for both. )
10. Write a Python program access the index of a list. add this index to all even numbers in the list and subtract it from all odd numbers and store your results in a new list. Print the new list. 

11. Create an empty list and add numbers from 1-30 using for loops.
"""

# 1. Write a Python program to sum all the items in a list. Create lists with at least 6 -----> take list items as number to add all items in a list

x = [24,45,12,23,45,1,2,3,45,5]
#print(sum(x))
sum = 0
for i in x: 
  sum = sum + i
  #print(sum, i)
  if i == x[3]:  # if want to add some specified range of numbers in the list only
  break

print(sum)

# 2. Write a Python program to multiply all the items in the list created in (1).

x = [24,45,12,23,45,1,2,3,45,5]
print(len(x))
mul = 1
for i in x :
  mul = mul * i #  mul * i = mul
  # 1st iteration   1 *  24 = 24
  # 2nd   '" "      24 * 45 = 1080
  # 3rd             1080 * 12 =

print(mul)

x = [24,45,12,23,45,1,2,3,45,5]
# sum = 0
mul = 1
i = 0
while i < len(x) :
  #sum = sum + x[i]
  mul = mul * x[i]
  i = i + 1
print(sum)
print(mul)

24 *45

24*45*12*23*45*1*2*3*45*5

# 3. Write a Python program to get the smallest number from a list.
x = [24,45,12,23,45,9,2,3,45,5]
small = x[0]
for i in x :
  if i <= small :
    small = i

print(small)

# 4. Write a Python program to count the number of strings where the string length is 2 or more and 
# the first and last character are same from a given list of strings. (Sample List : ['abc', 'xyz', 'aba', '1221'])
x = ['abc', 'xyz', 'aba', '1221']
count = 0
for i in x:
  if len(i) >= 2:
    if i[0] == i[-1] : # 
      count += 1  # count = count + 1
print(count)

#     012  
x = ['abc', 'xyz', 'aba', '1221']
#     0      1       2      3   ---> postive index
#    -4     -3      -2      -1   ----> negative index
for i in x :
  print(x[0])  # here x is a list----> 1st item in the list 
  print(i[0])    # here i is a string  --->in i variable, we are taking 1st charecter in the string
  print(i[-1])

x = ['abc', 'xyz', 'aba', '1221', "pop", 'high','pen' ]
count = 0
for i in x:
  if len(i) >= 2 and i[0] == i[-1] : # fist char in string has index num 0 ---> i.e x[0], last char ---> x[-1] in negative indexing
    count += 1  # count = count + 1
print(count)

# 5. Write a Python program to remove duplicates from a list.
x = [1,2,3,4,5,6,6,7,2,3,4]
new = []
for i in x :
  if i not in new:  # here it becomes true when the i value/item is not present in the new variable/list
    new.append(i)

print(new)

# 5. Write a Python program to remove duplicates from a list.
x = [1,2,3,4,5,6,6,7,2,3,4]
new = []
for i in x :
  if i in new :  # here it becomes true when the i value/item is not present in the new variable/list
    pass
  else:
    new.append(i)

print(new)

# 6. Write a Python program to check a list is empty or not. (look up)
x = []
if len(x) == 0 :
  print("List is Empty")

# 7. Write a Python program to clone or copy a list.
x = [1,2,3,4,5]
y = x.copy()   # or can write as y = x
print(y)

# 8. Write a Python program to find the list of words that are longer than 5 from a given list of words. create list with random animal names.

a = ["cat", "dog", "donkey", "giraffe","tiger","elephant", "monkey" ] 
count = 0
for i in a :
  if len(i) > 5:
    print(i, end = ",")
    count = count + 1
print("\n",count)

# 9. Write a Python program to get the difference between the two lists. (create two lists with numbers. List size should be at least 5 for both. )

a = ["cat", "dog", "donkey", "giraffe","tiger","elephant", "monkey" ] 
b = [1,2,3,3,4,5,5,"pen"]
print(len(a),len(b))
if len(a) > len(b):
  x = len(a)-len(b)
else:
  x = len(b)-len(a)
print(x)

# Write a Python program access the index of a list. 
# add this index to all even numbers in the list and subtract it from all odd numbers and store your results in a new list. Print the new list.

x = [11,22,32,42,52,62,72,82,99]
#     0 1  2  3  4  5   6  7  8
index = 0
even = []   # all even index values
odd = []  #  # all odd index values
for i in x:
  if index % 2 == 0 :   # to check the number is even or odd 
    #print(index+i, end = "")
    even.append(i)
  else:
    odd.append(i)
  index = index + 1

print(even)
print(odd)

x = [11,22,32,42,52,86,67,62,72,82,99, 75,43]
even = []
odd = []
for i in x:
  if i % 2 == 0 :
    even.append(i)
  else:
    odd.append(i)
print(even,odd)
#print(type(even))
# x1 =sum(even)
#print(x1)
x2 = sum(odd, 0)
print(x2)

22+ 32+ 42+ 52+ 62+ 72+ 82
sum = 0
for i in even :
  sum = sum + i
print(sum)

# 11. Create an empty list and add numbers from 1-30 using for loops.
x = []
for i in range(30):
  num = int(input("enter a number: "))
  x.append(num)
print(x)

l = ["cat", "dog", "donkey", "giraffe","tiger","elephant", "monkey" ]


for i in l:
  if len(i) >5 :
    print(i)

l = [10, 12,13,35,16,87,21,45,67,7 ]
a = ["cat", "dog", "donkey", "giraffe","tiger","elephant", "monkey" ]

print(len(l) - len(a))

x = 5
if x%2 == 0:
  print(x,"even")
else:
  print(x,"odd")

l = [10, 12,13,35,16,87,21,45,67,7 ]
sum  = 0
for i in l:
  sum = sum +i
print(sum)

l = [10, 12,13,35,16,87,21,45,67,7 ]
n =  len(l)
even = 0
odd = 0
for i in l :
  if i % 2 == 0:
    even = even + i
  else:
    odd = odd + i

if even > odd :
  print(even - odd)
else:
  print(odd - even)

l = [10, 12,13,35,16,87,21, ]
x = ["a", "n","y"]
#l.extend(x+l)
x =l.copy()  # here the l list is copied to the x variable
x = l 

print(l)
print(x)

x = [1,3,2,4,5,8,55]

sum = 0 # initalising the variable
for i in x :
  sum = sum + i
  # print(sum) ---> this print statement gives the output of the "sum" for 
  # sum = 0 + 1 = 1
  # sum =1, i = 3, => sum = 1 + 3 = 4, now sum = 4
  # sum = 4, i = 2 , => sum = 4 + 2 = 6


print(sum) # print statement is outside the for loop, because it should print the total / final "SUM" of the given List items

x = [5,3,2,4,5,8,55]

product = 1 # initalising the variable
for i in x :

  product = product * i

  # product = 1 * 5 = 5, product = 5 now----> new value for product
  # product = 5, i = 3, => product = 5 * 3 = 15, now product = 15
  # product = 15, i = 2 , => product = 15 * 2 = 30


print(product)

x = [5,3,2,4,5, 1,8,55]
small = x[0]
for i in x :
  if i < small:
    small = i

print(small)

x = [5,3,2,4,5,8,55]
print(len(x))
for i in x:
  print(i)

x = [5,3,2,4,5,8,55]
small = x[0] # small variable will store the 1st list item value of x variable
for i in  x :
  if i  < small :
    small = i   # when evre i is smaller than small variable then small will be storing the "i" value in it

print(small)





1+3+2+4+5+8+55
print(5*3*2*4*5*8*55)

l = [1,2,3,4,5,6,7]
sum = 0
for i in l :
  sum = sum + i

print(sum)

l = [7,2,3,4,5,1,6,7]
small = l[0]
for i in l:
  if i < small :
    small = i

print(small)



l = ["high", "hello", "tat", "Pop", "1231", "#78#"]
 count = 0  # count variable is used to count the no of items having same charecter on 1st & last  in the given list 
 x = []
 for i in l :
   if len(i) >1 and i[0] == i[-1] :
     x.append(i)
     count += 1 

print(x)
print(count)

L3 = ["Harry", "high", "Lakshmi", "It"]
count = 0
for term in L3:

  if len(term) > 1 and term[0] == term[-1] :
    print(term)
    count = count + 1
    
    
print(term)



Hint : - Q4 

  count = 0

  for word in words:
    if len(word) > 1 and word[0] == word[-1]:  # here i[0] means--> first char in the string, 
                                               #& i[-1] --> -1 means in negative indexing its the last letter of the string
      count += 1

words = ['aba', 'edf', '121', '55665', 'totopt', 'wow', '888']
count = 0 

for i in words :
  if len(i) > 1 and i[0] == i[-1] :        # here i[0] means--> first char in the string, 
                                               #& i[-1] --> -1 means in negative indexing its the last letter of the string
      count += 1     # count = count + 1
      print(i, end = "\t")   # here after printing all the i values, it stays in same line due to "\t" 
print("\n")
print("the count of words with same charecter in 1st & last is ",count)

"""###Python Membership Operators
Membership operators are used to test if a sequence is presented in an object:

Operator	Description	Example	Try it
```
in 	        Returns True if a sequence with the specified value is present in the object	          x in y	
not in	    Returns True if a sequence with the specified value is not present in the object       	x not in y
```

"""

x = ["apple", "banana"]

print("pineapple" not in x)

# returns True because a sequence with the value "pineapple" is not in the list

x = ["apple", "banana"]

print("banana" in x)

# returns True because a sequence with the value "banana" is in the list

# Write a Python program to remove duplicates from a list.

x = [1,2,"B",3,4, "B",5,"A",3,4 ,"B",5, "C"]
new_list = []
for i in x:
  if i not in new_list :
    new_list.append(i)

print(new_list)

# Write a Python program to remove duplicates from a list. --> another way with dict.formkeys()
x = [1,2,"B",3,4, "B",5,"A",3,4 ,"B",5, "C"]
new = list(new.fromkeys(x))  # or can use new = list(dict.fromkeys(x))    

# here dict.formkeys(list_name) will remove duplicate keys & creates a  updated dict  
# and list() will convert dict to list
print(new)

help(list)

# Write a Python program to check a list is empty or not.

# list = input()

l = []
x = [1,2,3]
z = []
for i in l, x, z :     # here l,x are 2 lists given in a sequence
  if len(i) == 0 :
    print("its a empty list")
  else :
    print ("the list is having {} items in it".format(len(i)))

x = []
if len(x)== 0:
  print("its an empty list")
else:
  print("the list is having {} items in it".format(len(i)))

# Write a Python program to clone or copy a list.
l = [1,2,3,4,5,6]
x = l.copy()
x

# by Using the extend() method
li_copy = [] 
li_copy.extend(li1)

Using the extend() method

help(list)





# Write a Python program to get the difference between the two lists. (create two lists with numbers. List size should be at least 5 for both. )
a = [1,2,3,4,7,5,67,9]
b = [3,4,5,6,7,8,9,3,2,4,5,6]

result = len(a) - len(b)
print(result)

a = [1,2,3,4,7,5,67,9]
b = [3,4,5,6,7,8,9,3,2,4,5,6]

if a>b:
  result = len(a) - len(b)
else:
  result = len(b) - len(a)
print(result)



#Write a Python program access the index of a list. add this index to all even numbers in the list and subtract it from all odd numbers and store your results in a new list. 
#Print the new list.

x = ["a", "b", "c", "g", "f","j","y"]
print(len(x))
even =[]  # even_index
odd = []
for i  in range(0,len(x)):
  if i%2 == 0:
    even.append(x[i])
  else:
    odd.append(x[i])

print(even)
print(odd)