# -*- coding: utf-8 -*-
"""Revision_Basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2iyWCqntfyKKQzKJ7nZCx8x2QIFC_hc
"""

1. Print First 10 natural numbers using for loop
2. Print First 10 natural numbers using while loop
Print First 10 natural numbers in reverse order using while loop
Display -10 to -1 using for loop

Accept number from user and calculate the sum of all number between 1 and given number
Print multiplication table of given number (using for loop) 
Given a list iterate it and display numbers which are divisible by 5 and if you find number greater than 150 stop the loop iteration

1. Write a python program to find largest number among 3 numbers.
2. Write a python program to find smallest number among 3 numbers.
3. Write a python program to find the given number is even/odd number 
4. Write a python program to find the given number is even/odd number in a list of numbers.
5. Write a python program to find the given number is prime number or not in a list.
6. Write a python program to find the factorial of given number.

"""**Solve the following**
1. Print First 10 natural numbers using while loop
2. Print the following pattern - pyramid/triangular

    1 

    1 2 

    1 2 3 

    1 2 3 4 

    1 2 3 4 5

3. Accept number from user and calculate the sum of all number between 1 and given number
4. Print multiplication table of given number
5. Given a list iterate it and display numbers which are divisible by 5    and if you find number greater than 150 stop the loop iteration
6. Given a number count the total number of digits in a number
  Print the following pattern using for loop
  
  5 4 3 2 1 

  4 3 2 1 

  3 2 1 

  2 1

  1

7. Reverse the following list using for loop
list1 = [10, 20, 30, 40, 50]
8. Display -10 to -1 using for loop

9. creat a code as mini calculator to do add, subtract, multiply, division etc.


"""



while condition :   # while loop execute when ever the condition is true
  body

"""https://colab.research.google.com/drive/1Tj-6ZGiDyicSCAEpMR8sxe6-hc8PXbYo?usp=sharing - printing pattrens"""

# Print First 10 natural numbers using while loop
i = 0
while i <  11 :  # to print 10 num, we can write i <= 10 or  i <11
  print("before",i)
  i += 1    # i = i+1 incrementing the i value 
  print("after increment" ,i)

# print numbers from 200 to 210, with while loop & for loop
i = 200
while i <= 210:
  print(i)
  i = i + 1

#print numbers from 210 to 200, with while loop & for loop
i = 210
while i >= 200 :
  print(i)
  i = i -1

for i in range(210,199, -1) :
  print(i)

i = 1
while i <= :   # or can give as i <21
  print(i)
  i = i + 1

while i in range(0,8):
  print(i )

Print the following pattern - pyramid/triangular

1

1 2

1 2 3

1 2 3 4

1 2 3 4 5

for i in range(1,6): #i= 1, i =2, i = 3     ---> 5 rows
  for j in range(1,i+1) :  #  j= 1,                 ---> is used to give how many columns in each row
    print(j, end = "\t")  # belongs to the 2nd for loop

  print("")

for i in range(5): #i= 0, i =1, i = 2     ---> 5 rows
  for j in range(i+1) :  #  j= 0,                 ---> is used to give how many columns in each row
    print(j, end = "\t")  # belongs to the 2nd for loop

  print("")

rows = int(input("enter how many rows you need to print: "))
for row in range(1,rows+1):
  for col in range(1, row +1) :
    print(col, end = "  ")
  print("")

for j in range(1,2) :  
    
  print(j)

# Accept number from user and calculate the sum of all number between 1 and given number



"""### Using "while" loop"""

rows = int(input("enter how many rows you need to print: "))
row = 1
while row <= rows:
  col = 1  #here its should be one so that we could inc coloumns from 1 to row number
  while col <= row:
    print(col, end = "  ")
    col = col + 1
  print("")
  row = row + 1





phone = { "amma" : 9999992342, "mama" : 8888883456, "nana" : 9988998899, "atha": 8899667755, 
         "bro" : 9898987676, "akka" : 99999443322 }
name = input("enter the contact name u are searching: ")
if name in phone :
  a = input ("contact found, Do u want the phone number : ")
  if a.lower() == "yes" :
    print(f"The phone number of {name} is {phone.get(name)}")
    print("The phone number of {} is {}".format(name,phone.get(name)))

else :
  print("Contact not found")

when you from random import *, all the definitions from random become part of the current name space. 
This means you don't have to prefix anything with random., but it also means you may get a name collision without even knowing it.

The preferred way is import random.



print(x.update({"color" : "red", 5 : "five"}))





# Question 6: Given a number count the total number of digits in a number

x=int(input("Enter number to get number of digits:  "))
y=0
if(x<0):
  print("Negative numbers not allowed !!")
elif(x==0):
  print("The number of digit:",1)
else:
  while(x>0):
    y+=1
    x=x//10   # gives the quoteinet in integer datatype
  print("The number of digit:",y)

567//10

Create code to manage transactions in a bank. It should contain
1. User details in a dictionary: Username, account numbers, pin number in list format
2. Use while loop to control the iteration of the loop. 
  a. ask for account number and match the details to the ones in the dictionary. If True, proceed with transaction. If false, account doesnt exist
  b. Ask for the correct pin numbers and match correctly.
  c. Perform deposit of funds, withdrawals, and display of balance.

https://colab.research.google.com/drive/1Tj-6ZGiDyicSCAEpMR8sxe6-hc8PXbYo?usp=sharing - printing pattrens

https://www.geeksforgeeks.org/python-program-to-create-bankaccount-class-with-deposit-withdraw-function/





"""## Reverse right angle trinagle"""

# Given a number count the total number of digits in a number Print the following pattern using for loop - reverse pattren

rows = int(input("enter the rows: "))
for i in range(rows,0,1):  
  for j in range(i,0,-1):
    print(j, end = " ")
  print("")





Create code to manage transactions in a bank. It should contain
1. User details in a dictionary: Username, account numbers, pin number in list format
2. Use while loop to control the iteration of the loop. 
  a. ask for account number and match the details to the ones in the dictionary. If True, proceed with transaction. If false, account doesnt exist
  b. Ask for the correct pin numbers and match correctly.
  c. Perform deposit of funds, withdrawals, and display of balance.

# manage transactions in a bank. 

details = { "username": ["lakshmi", "saisree", "samhitha", "sreeram"],
         "account_numbers" : ["12345678", "12345679", "12345677", "12345667"] ,
        "pin numbers" : [1111, 2222, 3333, 4444],
        "balance" : [10000, 20000,30000,40000]
        }

print(details.values())
while True : 


  print("Hii User")
  name = input("please Enter your username: ")
  if name in ["lakshmi", "saisree", "samhitha", "sreeram"] :
    check_account = input("type account number: ")
    if check_account in ["12345678", "12345679", "12345677", "12345667"] :
      print("1. Deposit of Funds \n2.WithDrawals \n3.Display of Balance")

      print(" Select your desired option:")
      select = input("please type only numbers from 1 to 3: ")

      if m == 1:
      
      elif m == 1
      elif  m== 2

      else : 

      ask = input("want to run any task:")
      if ask == "yes" ::
        pass
        print("")
      else:
        break


    else : 
      print("account doesnt exist")

  else :
    print("Your username is not Valid")
    print("Try again")

  
  break



help(dict)

bank = {"Usernames" : ["Sreeram@m.in","Samhitha@m.in","Lakshmhi@m.in","SaiSree@m.in"], 
        "Accounts" : ["123456","234576","345678","456789"], 
        "Pins" : ["123","234","345","456"]

dic = { "key_name1" : "value1", "key2" : "value2"}

#Bank Transactions:
details={"username": ["Lakshmi", "Sai Sree", "Sreeram", "Samhitha"],
         "account_numbers": ["12345678", "12345679", "12345677", "12345667"],
         "pin numbers":[1111,2222,3333,4444],
         "balance": [10000,20000,30000,40000]
         }
while True:


  print("Hi user.")
  name=input("Please enter your username.")
  if name in  ["Lakshmi", "Sai Sree", "Sreeram", "Samhitha"]:
    check_account= input("Please enter your account number:")
    if check_account == ["12

#Bank Transactions:
details={"username": ["Lakshmi", "Sai Sree", "Sreeram", "Samhitha"],
         "account_numbers": ["12345678", "12345679", "12345677", "12345667"],
         "pin numbers":[1111,2222,3333,4444],
         "balance": [10000,20000,30000,40000]
         }
while True:


  print("Hi user.")
  name=input("Please enter your username.")
  if name in  ["Lakshmi", "Sai Sree", "Sreeram", "Samhitha"]:
    check_account= input("Please enter your account number:")

    if check_account == ["12345678", "12345679", "12345677", "12345667"]:
          print("1. Deposit of funds. \n 2. Withdrawals \n 3. Display current balance" )
          print("Select your desired choice:")
          select= input("Please type numbers only from 1 to 3:")
        
            #update=
    else:
          print("Account does not exist")
  else:
   print("Your username is not valid. \n Please try again.")
  break

details={"username": ["Lakshmi", "Sai Sree", "Sreeram", "Samhitha"],
         "account_numbers": ["12345678", "12345679", "12345677", "12345667"],
         "pin numbers":[1111,2222,3333,4444],
         "balance": [10000,20000,30000,40000]
         }
name=input("Please enter your username.")
if name in details.values("username"):
    check_account= input("Please enter your account number:")