# -*- coding: utf-8 -*-
"""Ticket booking system .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0dhv8kMuhJ8upianJ3dxiLr7R70PkVx
"""



"""Create a bus reservation system. The system should have the following feaures. Fares: 
1. Hyderabad-bangalore--400 rs
2. Delhi - Pune -- 700 rs
3. Hyderabad- Delhi -- 1000 rs
4. Chennai - Bangalore -- 900 rs




"""

#1 Find route to be taken
#2. If tickets>5, apply 50% discount. 
#3. Children below 10 will travel free.

1. ask the user to which route they want to travel  ---->   Only one route bookable
2. then ask the user how many seats/tickets they want to book
3.then type the details for each ticket/seat ----> like name, age, gender etc
4. then calculate the fare/total price according to the  no of tickets.

# add then
1. add different prices for adults & children, 
i.e 1. 30% for tickets above 5
    2. Children <10 free

# Quiz
Create a bus ticketing system that gives discounts as per above problem and:
0% discount for 1 ticket
1% discount for 2 tickets
20% discount for 3 tickets
40% discount for 4 tickets



Create a bus reservation system. The system should have the following feaures. Fares:
Ban-Hyd - 500 rs
Chen-Ban -700
Chen-Koch - 500
Pune-Bom - 600
Bom-Del - 900

1. 30% for tickets above 5
2. Children <10 free 
3. Only one route bookable





no_of_tickets = int(input("Eneter no of tickets to be booked: "))
booking_details = []
#booking_details.fromkeys()

get_details = ["name", "age","gender"]
x = []  # to store each person/seat details in a list

print("\n")
for i in range(1,no_of_tickets+1):
  # x = []
  for d in range(len(get_details)):
    collect = input(f"enter the {get_details[d]} for booking seat no {i} :")
    x.append(collect)
  print("\n")
    
  booking_details.append(x)
  #print(booking_details)
  # x.clear()  ----> it will make clear in the 2 lists, x & booking details, so instead keep x= [] will cover  


print(booking_details)

# Full logic code
book = {"Hyd-Bag" : 1000, "Hyd-Vizag": 800, "hyd-Mub" : 1200}
while True :
  route = input("Enter the route: ")
  if route in book:

    no_of_tickets = int(input("Enetr nof of tickets to be booked: "))
    booking_details = []
    #booking_details.fromkeys()

    details = ["name", "age","gender"]
    print("\n \t\t please enter the details for booking Seats : \t\t \n".upper())

    for i in range(1,no_of_tickets+1):
      x = []  # to store each person/seat details in a list
      for d in range(len(details)):
        collect = input(f"Enter the {details[d]} for booking seat no {i} :")
        x.append(collect)
      print("\n")
      booking_details.append(x)
      # x.clear()  ----> it will make clear in the 2 lists, x & booking details, so instead keep x= [] will cover  
    
    # calculate the fare:
    print(f"The total fare for {no_of_tickets} tickets is {no_of_tickets*book.get(route)}")
    ask_pay = input("Go to payment : ")   # Proceed to Pay / click to payment
    if ask_pay == ["y", "yes", "Y", "YES", "ok", "OK"] :
      # Type the amount to be paid
      print("\n Successfully completed the transcation !!!!! \n")


  print(f"The details for booking {no_of_tickets} are:  ")
  s = 1
  for j in booking_details:
    print(f"Seat {s}  :  {j}")
    s= s+1
  ask = input("Do want to book any other tickets:")

  if ask.lower() == 'yes':   # or can write like this ask == ["y", "yes", "Y", "YES"]
    pass
  else:
    print("Thank you for visiting the site")
    break



x = []
y = [1,2,3]
x.append(y)
y = []
# y.clear()  ----> it will make clear the x value where ever it added 

print(x)



# using dictonaries for storing booking details 
book = {"Hyd-Bag" : 1000, "Hyd-Vizag": 800, "hyd-Mub" : 1200}
while True :
  route = input("Enter the route: ")
  if route in book:

    no_of_tickets = int(input("Enetr nof of tickets to be booked: "))
    booking_details = {}
    details = ["name", "age","gender"]
    print("\n \t\t please enter the details for booking Seats : \t\t \n".upper())

    for i in range(1,no_of_tickets+1):
      x = []  # to store each person/seat details in a list
      for d in range(len(details)):
        collect = input(f"Enter the {details[d]} for booking seat no {i} :")
        x.append(collect)
      print("\n")
      booking_details.fromkeys(x)
      print(booking_details)

no_of_tickets = int(input("Enetr nof of tickets to be booked: "))
booking_details = {}
details = ["name", "age","gender"]
print("\n \t\t please enter the details for booking Seats : \t\t \n".upper())
for i in range(1,no_of_tickets+1):
  x = []  # to store each person/seat details in a list
  for d in range(len(details)):
    collect = input(f"Enter the {details[d]} for booking seat no {i} :")
    x.append(collect)
  print("\n")
  booking_details.fromkeys(x)
  print(booking_details)

d = {}
x= ["name","age", "gender"]
#d = d.fromkeys(x)
name = input("Enter the name: ")
kage = input("Enter the age: ")
#gender = input("Enter the gender: ")
d.update(n = name, age = age )
d.setdefault((x[0]), name)  # possible with tuples to add as key name with list
#d.update({})

print(d)

x= ["name","age", "gender"]
y = (x[0], x[1])
print(y)

# bill printer
# we will assign for each item certain price using dictonary datatype
# we access the price of a particular item using get() method or x["key"] ----> so we get the value of the particular key
# we use if cond to check what item they have typed, & print the price
# & then calculate the total cost of the items he has bought



# bill printer

x= {"coffee": 500, "milk": 100, "soaps": 600, "veggies": 300, "pulses": 800 }

while True:
  items =



x= {"coffee": 500, "milk": 100, "soaps": 600, "veggies": 300, "pulses": 800 }
# total = []
total = 0
a= input()
print(x["coffee"] + x["veggies"] + x["milk"] )
print(x.get(a) + x.get("milk") + x.get("soaps"))
# x = x+1
print(type(x.get(a)))
total = total + x.get(a)
print(total)