# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZI31koItISOwXg94-okgC4SYZIzXv7s

https://docs.python.org/3/library/functions.html?highlight=functions  - info abt in built functions

#Python Variables

**Variables are containers for storing data values.**

Unlike other programming languages, Python has no command for declaring a variable.

A variable is created the moment you first assign a value to it.

#Variable Names
A variable can have a short name (like x and y) or a more descriptive name (age, carname, total_volume). 
##Rules for Python variables: 
* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)

# Keywords 
 * we cannot use keywords as a variable names, as the key words has some specific task to be done in the python language
"""

import keyword
print(keyword.kwlist)

a = 1   # here we are assigning number data to the variable "a"
b = 2 
name = "lakshmi"  # we need to use "" or '' for writing a text or characters
print(a)  # when we write the variable name in print() function , it will print the value of that variable
print(b)
print(name)

"""### *Rules for Variables*
1. Can start with capital letters e.g Led
2. Can have all small letters e.g led
3. Can start with an underscore e.g. _led, __LED

### Note:

* 1num, 1_num ect are not the valid variable names
"""

LED1 = 4
LED2 = 5
LED3 = 6

Variable = value
#variable  is also called an identifier
#A variable is a special kind of an identifier
#An identifier can be a variable, object, class, function, list, dictionary, tuple

first_name = "lakshmi"  # its a string datatype
                        #  String should be write evry time in "" or '' double or single Quotes.



"""##Data types in Python
Every value in Python has a datatype. Since everything is an object in Python programming, **DATA TYPES** are actually **CLASSES** ,and **variables** are **instance (object)** of these classes.

There are various data types in Python. Some of the important types are listed below.

**Built-in Data Types**

In programming, data type is an important concept.

Variables can *store data of different types, and different types can do different things.*   

Python has the following data types built-in by default, in these categories:

* **Text Type :**	str
* **Numeric Types :**	int, float, complex
* **Sequence Types :**	list, tuple, range(is not particulaly a data type, range is a function)
* **Mapping Type :**	dict
* **Set Types :**	set, frozenset
* **Boolean Type :**	bool
* **Binary Types :**	bytes, bytearray, memoryview

it means they r ready & built in python language & we can use them directly, means no need to create them & then use it, they r in built

Data types are nothing but its like representing a kinds of languages [ like numbers, alphabets, words, text/sentences, list etc] which we will be used to present/give the data/information which we want in our python programs or in python languages

#Standard Variables


1. Number - integer, float, complex number

  int - integer - eg 1, 2, 3, 4, etc
  
  float - float - eg. 1.2, 4.5, 3.6, 3.14159 => 22/7,
  
  complex numbers - a + jb e.g 4.53e-7j

2. String - str eg. 'mango', 'potato', 'fish', 'apple', '5', '2.342', "7677.233"

3. Lists - ['a', 'b', 'apple', 'Banana', '4', 6, 8, 1.2] - square 

4. Tuples - ('a', 'b', 'apple', 'Banana', '4', 6, 8, 1.2) - parenthesis

5. Dictionary - {'a': 'b', 'apple', 'Banana', '4', 6, 8, 1.2} - curly

**Python Numbers**

Integers, floating point numbers and complex numbers fall under Python numbers category. They are defined as int, float and complex classes in Python.

We can use the **type()** function to know which class a variable or a value belongs to. Similarly, the **isinstance()** function is used to check if an object belongs to a particular class.
"""

import keyword
print(keyword.kwlist)

Name = input("Enter your name :") 
print("hello ",Name, "have a nice day")

int()
input()

num1 = int( input("enter yor 1st number: ") )  # by default it takes the value as string, 
num2 = int(input("enter yor 2nd number: ")   # to convert from string to int we use int() function
print(num1 + num2)
print("hi" +""+ "wolrd")

#data types  - is collection of information according to the types of it/information
In numbers we have 3 types ;

integers  - 1,2 ,3 , -1, etc
floats - 4.0
complex - 2+5i , 6+9i

Python Numbers
There are three numeric types in Python:

int
float
complex

print(type([1,2,3,4]))
print(type(9))

z = 1+2j
x = 5j
print(x)
z

x = 1    # int
y = 2.8  # float
z = 1j   # complex

print(type(x))  # type function tells u the variable belongs to which data type
print(type(y))   # type() is a fun used to know which data type it belongs to
print(type(z))

Python Strings
String Literals
String literals in python are surrounded by either single quotation marks, or double quotation marks.

'hello' is the same as "hello".

String Concatenation
To concatenate, or combine, two strings you can use the + operator.

int("5") #function will convert the given data (particularly the stirng numbers) into integer
str(5)

x = int(input("enter ur number : ")) # by default input() method will store the value/data as a STRING.
y = int(input("enter ur number : "))
sum = x + y
print("sum of {} and {} is {}".format(x,y,sum))
print( "sum of", x , "and", y, "is", sum)
print( "sum of"+ x + "and"+ y + "is"+ sum)

name = input("enter the name: ")
greeting = input("Enter your greeting: ")
print("Hi", name, greeting)

# calculate your AGE 

DOB = int(input("enter your date of birth year: "))
P_year = int(input("enter the current year:"))
age = P_year - DOB
print("Your age is: ", age)

x = 4.1
y = 5.0
z = 7

print(int(x+z))
print(x-y)

Converting function - int(), float(), str()

"""## Built-in Functions
The Python interpreter has a number of functions and types built into it that are always available.

They are listed here in alphabetical order. --> https://docs.python.org/3/library/functions.html  ,  https://www.w3schools.com/python/python_ref_functions.asp

## input() function - 

input(prompt) --> Allowing user input , here prompt is a parameter we can pass in function.

prompt --->	A String, representing a default message before the input.

input ( prompt) : This function first takes the input from the user and then evaluates the expression, which means Python automatically identifies whether user entered a string or a number or list. If the input provided is not correct then either syntax error or exception is raised by python. For example –

How the input function works in Python :

* When input() function executes program flow will be stopped until the user has given an input.
* The text or message display on the output screen to ask a user to enter input value is optional i.e. the prompt, will be printed on the screen is optional.
* Whatever you enter as input, input function convert it into a string. if you enter an integer value still input() function convert it into a string. You need to explicitly convert it into an integer in your code using typecasting.

"""